//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WallaceFarms
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeefOrder
    {
        public int BeefOrderID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> ButcherID { get; set; }
        public Nullable<int> NumQuarters { get; set; }
    
        public virtual Butcher Butcher { get; set; }
        public virtual Order Order { get; set; }
    }
}
