//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WallaceFarms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Butcher
    {
        public Butcher()
        {
            this.BeefOrders = new HashSet<BeefOrder>();
        }
    
        public int ButcherID { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
    
        public virtual ICollection<BeefOrder> BeefOrders { get; set; }
    }
}
